### ISSUE TITLE
README

### ISSUE THREAD

**Issue by lKak0l** [SpiralBL0CK/Mallicious-IOS-SHORTCUT-KEYLOGGER-#1]
Hi bro... Could you explain the procedure? and what does the encrypted code do. very thnx mch :)

**Comment by SpiralBL0CK** [comment]
ye sure so enc is rot13  which decodes a css keylogger and than read https://medium.com/@chrishutchinson/hacking-around-with-javascript-and-shortcuts-in-ios-12-95f8d7190777 to get the hang of it

**Comment by SpiralBL0CK** [comment]
ye sure so enc is rot13  which decodes a css keylogger and than read https://medium.com/@chrishutchinson/hacking-around-with-javascript-and-shortcuts-in-ios-12-95f8d7190777 to get the hang of it

**Comment by lKak0l** [comment]
ios 12 ...

**Comment by SpiralBL0CK** [comment]
well idk idk rlly :) i was just experimenting :) don't alaways expect for me to get stuff :) srry >/.> what can i say i like to experiment sometimes. idk :) sry baws man
